define([
  './animation/index',
  './components/index',
  './Animation',
  './Audio',
  './Button',
  './ComponentContainer',
  './Container',
  './Easing',
  './Game',
  './LoadingScreen',
  './MovieClip',
  './Shapes',
  './Sprite'
], function(animation,
            components,
            Animation,
            Audio,
            Button,
            ComponentContainer,
            Container,
            Easing,
            Game,
            LoadingScreen,
            MovieClip,
            Shapes,
            Sprite) {
  return {
    animation: animation,
    components: components,
    Animation: Animation,
    Audio: Audio,
    Button: Button,
    ComponentContainer: ComponentContainer,
    Container: Container,
    Easing: Easing,
    Game: Game,
    LoadingScreen: LoadingScreen,
    MovieClip: MovieClip,
    Shapes: Shapes,
    Sprite: Sprite
  }
});
